var empId;
empId = 123;
console.log(empId);
console.log(typeof empId);
empId = "e123";
console.log(empId);
console.log(typeof empId);
empId = true;
console.log(empId);
console.log(typeof empId);
var empAddress;
empAddress = "Dhari road ,delhi";
var lowerstring = empAddress.toLowerCase;
console.log(lowerstring);
var empSalary;
var city;
city = "mumbai";
console.log(city);
var company = "Neosoft technology";
document.write(company);
document.write(typeof company);
var num1 = 67;
var num1 = 78;
console.log(num1);
var num2 = 45;
num2 = 23;
var num3 = 11;
