USE mydb;

SELECT * FROM EMP;

SELECT JOB,SAL,DEPTNO FROM EMP;
SELECT EMPNO,SAL AS oldsal,(SAL*1.05) AS newsal FROM EMP;
SELECT 100*1.05 AS RESULT;

SELECT EMPNO,SAL FROM ORDERBY EPMNO,SAL;

select * FROM EMP;

SELECT EMPNO,ENAME FROM EMP WHERE SAL>1200 order by EMPNO DESC;

SELECT * FROM EMP WHERE SAL>800 AND SAL<3000 AND DEPTNO>20;

SELECT * FROM EMP WHERE SAL<1000 OR SAL>1600;

SELECT * FROM EMP WHERE SAL between 1200 AND 1600;

SELECT * FROM EMP WHERE SAL NOT between 1200 AND 1600;

SELECT * FROM EMP WHERE JOB IN('CLERK','MANAGER','PRESIDENT');
SELECT * FROM EMP WHERE JOB NOT IN('CLERK','MANAGER','PRESIDENT');

SELECT * FROM EMP WHERE SAL IN(1600,1200,800) AND DEPTNO>20;

SELECT * FROM EMP WHERE ENAME LIKE 'A%';
SELECT * FROM EMP WHERE ENAME LIKE '_A%';
SELECT * FROM EMP WHERE ENAME LIKE '_AR%';
SELECT * FROM EMP WHERE ENAME LIKE '%D';
SELECT ENAME FROM EMP WHERE ENAME LIKE 'A%';

SELECT * FROM EMP LIMIT 5;
SELECT ENAME FROM EMP LIMIT 5;

SELECT * FROM EMP WHERE JOB IN('CLERK','MANAGER','PRESIDENT') order by EMPNO LIMIT 2,5;

SELECT * FROM EMP WHERE COMM IS NULL;
SELECT * FROM EMP WHERE COMM IS NOT NULL AND MGR IS NULL;
SELECT * FROM EMP WHERE COMM IS NULL AND MGR IS NULL;

SELECT * FROM EMP;
SELECT SAL FROM EMP;

SELECT distinct JOB FROM EMP;
SELECT distinct SAL FROM EMP;
SELECT distinct COMM FROM EMP;

SELECT ename,job,sal AS oldsal, (SAL*0.90) AS newsal FROM emp WHERE job IN ('MANAGER'); -- SECOND Last

SELECT * FROM emp WHERE job IN ('CLERK','PRESIDENT') ORDER BY sal DESC; -- First

SELECT ename,sal FROM emp WHERE ename LIKE '__R%' AND job IN ('SALESMAN'); -- Last

SELECT * FROM emp WHERE job IN ('MANAGER') ORDER BY empno DESC;

SELECT * FROM emp WHERE mgr IS NULL;	

SELECT ename,empno,sal FROM emp WHERE sal BETWEEN 2000 AND 6000 AND job IN ('MANAGER') AND mgr IN ('7839') ORDER BY sal DESC;

SELECT e.ENAME AS employee_name,e.sal as salary FROM EMP e;

SELECT MAX(SAL) AS MAXSAL,MIN(SAL) AS MINSAL,AVG(SAL) AS AVGSAL FROM EMP;

SELECT MAX(SAL) FROM EMP;

SELECT * FROM EMP WHERE SAL=(SELECT MAX(SAL) FROM EMP);

SELECT * FROM EMP WHERE SAL=(SELECT MAX(SAL) FROM EMP WHERE SAL<(SELECT MAX(SAL) FROM EMP));

SELECT E.ENAME FROM (SELECT * FROM EMP WHERE SAL<3000) AS E;

DESCRIBE EMP;

SELECT E.EMPNO,E.SAL,D.DNAME,D.LOC
FROM EMP E
INNER JOIN DEPT D ON E.DEPTNO=D.DEPTNO;

SELECT E.EMPNO,E.SAL,D.DNAME,D.LOC
FROM EMP E
INNER JOIN DEPT D USING (DEPTNO);

SELECT E.*,D.LOC
FROM EMP E
INNER JOIN DEPT D USING (DEPTNO);

SELECT COUNT(*) FROM (SELECT E.*,D.LOC
FROM EMP E
LEFT JOIN DEPT D USING (DEPTNO))X;

SELECT E.*,D.LOC
FROM EMP E
LEFT JOIN DEPT D USING (DEPTNO);

SELECT E.*,D.LOC
FROM EMP E
RIGHT JOIN DEPT D USING (DEPTNO);

INSERT INTO EMP VALUES(111,'xyz','clerk',null,null,2000,null,50);
INSERT INTO DEPT VALUES(60,'UNKNOWN','NA');

SELECT COUNT(*) FROM (SELECT E.*,D.LOC
FROM EMP E
LEFT JOIN DEPT D USING (DEPTNO))X;

SELECT E.*,D.LOC
FROM EMP E
LEFT JOIN DEPT D USING (DEPTNO);

SELECT E.*,D.LOC
FROM EMP E
RIGHT JOIN DEPT D USING (DEPTNO);

SELECT *
FROM EMP E
LEFT JOIN DEPT D USING (DEPTNO) WHERE D.DEPTNO IS NULL;

SELECT *
FROM EMP E
RIGHT JOIN DEPT D USING (DEPTNO) WHERE E.DEPTNO IS NULL;

SELECT COUNT(*) FROM (SELECT E.*,D.LOC
FROM EMP E
CROSS JOIN DEPT D)X;

SELECT *
FROM EMP E
LEFT JOIN DEPT D USING (DEPTNO)
UNION
SELECT *
FROM EMP E
RIGHT JOIN DEPT D USING (DEPTNO)


SELECT * FROM t1
LEFT JOIN t2 ON t1.id = t2.id
UNION
SELECT * FROM t1
RIGHT JOIN t2 ON t1.id = t2.id;  

SELECT COUNT(*) FROM EMP; -- 14
SELECT COUNT(*) FROM DEPT; -- 4




