USE MYDB;

SELECT COUNT(*) FROM EMP;

SELECT * FROM EMP;

SELECT DEPTNO,COUNT(*) AS COUNTER FROM EMP WHERE DEPTNO>10
GROUP BY DEPTNO ORDER BY 2 DESC LIMIT 2;

SELECT DEPTNO,COUNT(*) AS emps ,MAX(SAL) AS maxsal,
MIN(SAL) AS minsal FROM EMP GROUP BY 1;

SELECT DEPTNO,COUNT(*) AS emps
FROM EMP GROUP BY 1 HAVING emps > 4;

SELECT DEPTNO FROM EMP GROUP BY 1 HAVING MAX(SAL)>3000;

-- DIPLAY AVG SALARY-1
SELECT JOB,COUNT(*) AS emps ,AVG(SAL) AS sal FROM EMP GROUP BY 1;

SELECT *,COUNT(*) DEPTNO ,MAX(SAL) AS maxsal FROM EMP GROUP BY DEPT HAVING avg(SAL)>2000;

SELECT curdate();
SELECT CURTIME();
SELECT SYSDATE();

SELECT CURDATE(); -- Date
SELECT CURTIME(); -- Time
SELECT NOW(); -- Server time
SELECT SYSDATE(); -- System time

SELECT DATE_ADD('2021-10-25',INTERVAL 30 DAY); -- Year month day
SELECT DATE_ADD('2021-10-25',INTERVAL 1 YEAR);
SELECT DATE_ADD('2021-08-12',INTERVAL 3 MONTH);
SELECT DATE_ADD(CURDATE(),INTERVAL 30 DAY);
SELECT DATE_ADD(CURTIME(),INTERVAL 3 HOUR);

SELECT DATEDIFF('2021-08-12',CURDATE());
SELECT DAYNAME(CURDATE()),DAYOFMONTH(CURRDATE()),DAYOFWEEK(CURDATE()),DAYOFYEAR(CURDATE());
SELECT MONTH(CURDATE()),MONTHNAME(CURDATE()),YEAR(CURDATE()),WEEKOFYEAR(CURDATE());
SELECT HOUR(CURDATE()),MINUTE(CURTIME());

SELECT DATE_FORMAT('2021-10-26 16:12:00 ','%W %M %Y');
SELECT DATE_FORMAT('2021-10-26 16:12:00 ','%H : %I : %S');
SELECT DATE_FORMAT('2021-10-26 16:12:00 ','%D %M %Y %a , %d %m %b  : %j th day');

SELECT * FROM EMP;

-- 2. Count the most junior emps of the table.
SELECT * FROM emp ORDER BY hiredate DESC limit 1;

-- 3. Find out the empname, sal, deptno, dept location of most senior emp/emp's.
SELECT empno,ename,job,sal,loc,hiredate FROM emp INNER JOIN dept ON emp.deptno = dept.deptno ORDER BY hiredate limit 4 ;

SELECT E.ENAME,E.SAL,D.DEPTNO,D.DNAME FROM EMP E
INNER JOIN DEPT D
USING(DEPTNO) WHERE DATEDIFF(CURDATE(),E.HIREDATE)=
(SELECT MAX(DATEDIFF(CURDATE(),HIREDATE)) FROM EMP);

select period_diff(date_format(now(), '%Y%m'), date_format(hiredate, '%Y%m')) as months from emp;

INSERT INTO EMP VALUES('7999','AMAD','CLERK','7788','1983-01-15','1100.00',NULL,'20');

INSERT INTO EMP(ename,empno,sal,job) VALUES('XYZ',999,1200,'CLERK');

SELECT COUNT(*) as juniors FROM EMP WHERE 
period_diff(date_format(now(), '%Y%m'), date_format(hiredate, '%Y%m')) = 
(select MIN(period_diff(date_format(now(), '%Y%m'), date_format(hiredate, '%Y%m'))) FROM emp);

INSERT INTO EMP VALUES
('1999','JOHN','CLERK','7788','1983-01-10','1100.00',NULL,'20'),
('1999','SOURABH','CLERK','7788','1983-01-05','1100.00',NULL,'15'),
('3999','JOHN','CLERK','7788','1983-01-25','1100.00',NULL,'20');

INSERT INTO EMP(ENAME,EMPNO,SAL,JOB) SELECT ENAME,EMPNO,SAL,JOB FROM EMP;

SELECT * FROM EMP;

UPDATE EMP SET SAL=1600,COMM=500 WHERE DEPTNO IN(30,20);

SET SQL_SAFE_UPDATES=0;

DELETE FROM MYDB.EMP WHERE DEPTNO=30;

REPLACE INTO EMP(EMPNO,ENAME) VALUES('1999',ABCD);












